export interface Asociacion {  
    IdAsociacion: number,
    IdEntidad1: number,
    IdEntidad2: number,
    IdTipoAsociacion: number,
    TipoAsociacion: string,
    IdEstudiante: number,
    IdProfesor: number,
    IdEntidad: number,
    IdTipoEntidad: number,
    TipoEntidad: string,     
    Evaluacion: string,
    Estado: string,
    Comentario: string,   
}
